### ISSUE TITLE
测试一个GAC的新示例

### ISSUE THREAD

**Issue by jubeiot** [roodkcab/gacglobalstringdemo#1]
你好, 
看到有在测试使用GAClib, 我也在学习测试, 希望能有支持WebView (libCEF浏览器控件)的示例,你可以尝试一下吧!

**Comment by roodkcab** [comment]
哦，这个repo是为了演示一个编译xml的bug，并不是什么示例。你可以看doc那个项目，vczh说那个doc站是用gaclib开发出来的。
